### ISSUE TITLE
英译中

### ISSUE THREAD

**Issue by bigbigwanglei** [kok-s0s/Protect-face-information#1]
原句：For deep learning in particular, CUDA libraries such as cuBLAS [32] and cuDNN [33] provide highly-optimized implementation for a wide-range of standard primitives such as convolutions, pooling, activation functions, and more.

其中 convolutions, pooling, activation functions 是什么中文意思？

**Comment by GongZheng** [comment]
convolution就是卷积的意思

pooling就是深度学习中的专业术语，池化

activation function就是激活函数
